# Generated by Django 5.1.4 on 2025-01-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('0-18', '0-18'), ('18-35', '18-35'), ('36-50', '36-50'), ('51-65', '51-65'), ('65+', '65+')], default='18-35', max_length=5),
        ),
    ]
